# Generated by Django 4.0.2 on 2022-02-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Femal', 'Femal')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('identification_type', models.CharField(max_length=50)),
                ('identification_ID', models.CharField(max_length=50)),
                ('covid_test_result', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/%Y/%m/')),
                ('qr_url', models.URLField(blank=True)),
                ('time_deadline', models.DateTimeField(blank=True)),
                ('reset_deadline', models.CharField(choices=[('RESET', 'RESET'), ('NO-RESET', 'NO-RESET')], default='NO-RESET', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=255, unique=True)),
            ],
        ),
    ]
